version: '3'
services:
  server:
    build: 
      context: .
      dockerfile: serverDocker
    restart: always
  client:
    build: 
      context: .
      dockerfile: clientDocker
    restart: always
    depends_on: 
     - server
    links:
     - "server" 
  
